language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "oboehm-github"
    token:
      secure: "Kadw8e9EqyZToTmzy2C98TqrMJ3xxm09K2I/OuhMNvrtOGuFOm9MrXSDLecZfH05m6NFe45ZJjWMTIbPNRPr2HygnI8uWHAaM0DKMF+aq58exHbEPo+YyyXpgqgHrsZnHIxWtwAH+Q8XOdyjJgJdQJr04vRC0ylK+wCFmMJfBLy3GmZ72j2d59I7L+OyvlpoADJjFmqd5PXc8trC2+ahDqsmYuNGqEWfct7fqlNCAVs5SJBfd+LitrvvzeggIPDHVOFref0pBVP4mWIJXkY/9y/ody6iK0NPZs9T5csoc5n/bORQcXaHXjCVdMl/2dxAPJbwMoNWbzCdMyf60h5/IHhus5AyjX44r0z3BsOiUR04HFwNaSAI99bjv1E9UKTg82x2ZaRQReOatXCTuuSHckVIav23zBp5C3P/n2LqmXRmVHXkig6QzLrbsyGf5eNh1mktxBLQrrHvQLRrMRcDAAberwVHVnJ2awFyF3F9dDZR+U3H/cuG94KD/B8koijOUvjsyFmBxsZSf44d3zCe+74HAaPpELorg94B/bwqNJ3xw6bhgeMGDPy1eQ99C6VO8WHj0/8bSrfpMEoEWE7TIANK1dNWEtieQR9BNg2maXCQ8Vp1lYAWAF3CvRdrY/ISpHl9UOcnqndRPrToHducxG6Ib7RU+ofPoz0CNZNeNK4="
    branches:
      - master
      - develop

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B

after_success:
  - mvn integration-test jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
